package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void bubbleSort(T[] arr) {
        for (int i = 0; i < arr.length - 1; i ++) {
            for (int j = 0; j < arr.length - 1 - i; j++) {
                if (arr[j].compareTo(arr[j+1]) > 0) {
                    swap(arr, j, j+1);
                }
            }
        }
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void selectionSort(
            T[] arr) {
        // TODO: fill me in!
        for (int i = 0; i < arr.length - 1; i ++) {
            int minIndex = i;
            for (int j = i; j < arr.length; j++) {
                if (arr[j].compareTo(arr[minIndex]) < 0) {
                    minIndex = j;
                }
            }
            swap(arr, minIndex, i);
        }
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void insertionSort(T[] arr) {
        for (int i = 1; i < arr.length; i++) {
            T key = arr[i]; 
            int j = i - 1;
    
            while (j >= 0 && arr[j].compareTo(key) > 0) {
                arr[j + 1] = arr[j]; 
                j--;
            }
            arr[j + 1] = key;
        }
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void mergeSort(
            T[] arr) {
        if (arr.length <= 1) {
            return;
        }
        
        int mid = arr.length/2;
        T[] arr1 = Arrays.copyOfRange(arr,0,mid);
        T[] arr2 = Arrays.copyOfRange(arr,mid,arr.length);
        
        mergeSort(arr1);
        mergeSort(arr2);
        
        merge(arr,arr1,arr2);
    }

    public static <T extends Comparable<? super T>> void merge(T[] arr, T[] arr1, T[] arr2) {

        int i = 0, j = 0, k = 0;

        while (i < arr1.length && j < arr2.length) {
            if (arr1[i].compareTo(arr2[j]) <= 0) {
                arr[k] = arr1[i];
                k++;
                i++;
            } else {
                arr[k] = arr2[j];
                k++;
                j++;
            }
        }
        while (i < arr1.length) {
            arr[k++] = arr1[i++];
        }

        while (j < arr2.length) {
            arr[k++] = arr2[j++];
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> void quickSort(T[] arr) {
        quickSortHelper(arr, 0, arr.length - 1);
    }

    private static <T extends Comparable<? super T>> void quickSortHelper(T[] arr, int low, int high) {
        if (low < high) {
            int pivotIndex = pivotGetter(arr, low, high);
            quickSortHelper(arr, low, pivotIndex - 1); // Sort left half
            quickSortHelper(arr, pivotIndex + 1, high); // Sort right half
        }
    }

    private static <T extends Comparable<? super T>> int pivotGetter(T[] arr, int low, int high) {
        int pivotIndex = medianOfThree(arr, low, high);
        T pivot = arr[pivotIndex];

        // Move pivot to end
        swap(arr, pivotIndex, high);

        int i = low - 1;

        for (int j = low; j < high; j++) {
            if (arr[j].compareTo(pivot) <= 0) {
                i++;
                swap(arr, i, j);
            }
        }

        // Place pivot in correct position
        swap(arr, i + 1, high);
        return i + 1;
    }

    private static <T extends Comparable<? super T>> int medianOfThree(T[] arr, int low, int high) {
        int mid = low + (high - low) / 2;

        // Move the median to index mid
        if (arr[low].compareTo(arr[mid]) > 0) {
            swap(arr, low, mid);
        }
        if (arr[low].compareTo(arr[high]) > 0) {
            swap(arr, low, high);
        }
        if (arr[mid].compareTo(arr[high]) > 0) {
            swap(arr, mid, high);
        }
        return mid;
    }

}
